language: java

jdk:
  - oraclejdk9

services:
  - docker

addons:
  sonarcloud:
    organization: ressec-github
    token:
      secure: "${SONAR_TOKEN}"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -f pom.xml
    -Dsonar.projectKey=ressec_kakoo-foundation

deploy:
  provider: script
  script: cp etc/deploy-settings.xml $HOME/.m2/settings.xml && mvn deploy -f pom.xml
  skip_cleanup: true # Prevent Travis CI from resetting the working directory and deleting all changes made during the build!
  on:
    tags: false

notifications:
  email:
    recipients:
      - christophe.resse@gmail.com
    on_success: change
    on_failure: always
  slack:
    rooms:
      # 'kakoo-softwares' is the Slack workplace.
      # 'travis-foundation' is the channel where Travis should inject posts for this project build.
      - kakoo-softwares:KlswspYHL1Uq2X2F7UUazdL6#travis-foundation
